### ISSUE TITLE
Unable to get forecast!

### ISSUE THREAD

**Issue by lexterror** [ajwarnick/forecast-js#4]
The only forecast I get is for 90210! i tried some local zip codes and they dont give a forecast. I live in Boston!

Thank you!

**Comment by lexterror** [comment]
New York works as well... Im not getting any data for Massachusetts!

Thank you!

**Comment by ajwarnick** [comment]
What zip isn't working? and do you have your code some place i can see it?
The 90210 is set in an attribute if you want to change it:
`<div class="results" id="app" data-default-zip="90210">`

**Comment by lexterror** [comment]
Hi ajwarnick!!!

Every single zip for Massachusetts that I've tried does not return any data! (02135, 02465, etc....)

Thank you!

**Comment by ajwarnick** [comment]
Thanks, I think the issue is how the zip code api deals with zipcodes that start with 0. I opened a more specific issue if you want to follow my progress.

**Comment by lexterror** [comment]
Great! Thank you!!!

**Comment by ajwarnick** [comment]
Ok, should be working now please let me know if you have further issues.

**Comment by lexterror** [comment]
Thank you!!! It works!!!
