### ISSUE TITLE
Support: are the icons still working?

### ISSUE THREAD

**Issue by lexterror** [ajwarnick/forecast-js#7]
Im not getting any icons on either your website or the app! 

Thank you!

**Comment by lexterror** [comment]
I tried: 

if (forecast[0].icon == "skc")
{
	$("#day0").css("background", "url(" + clear.png + ")");
}

etc...

No luck!

**Comment by lexterror** [comment]
I finished trying:

if (gn.$forecast[0].icon == "skc")
{
	$("day0").css("background-image", "url(" + clear.png + ")");
}

still does not work!

**Comment by lexterror** [comment]
Got it! I had to add the <img src="">

Thank you!!!

**Comment by lexterror** [comment]
Thank you!!!

**Comment by lexterror** [comment]
Hi ajwarnick!!!

I have my weather app working now! It can be found here at the bottom of the page:

http://elounge.org

Thank you!!!

**Comment by ajwarnick** [comment]
if you are using vue this is the way i typically do my icons:

```html
<div class="icon" v-if="forecast[0].icon">
        <div
          v-bind:class=" 'icon_'+forecast[0].icon "
          style="height: 200px; width: 200px;"
        ></div>
        {{ forecast[0].icon }}
      </div>
```
you can see this on lines 125-132 on my [all example.](https://codesandbox.io/s/forecast-js-all-v201-kn5de?file=/index.html:4089-4304)

**Comment by lexterror** [comment]
Hi ajwarnick!

Since I last posted here I made some cool 3D Weather Icons with Blender 3D! They are simple, but they work visually in my opinion! I modeled/rendered them in Blender and made them into Animated GIFs with Gimp for my site! Feel free to use them as well! I could still improve them, but I just don't have the time! They look nice though! You can see them here: http://elounge.org at the bottom of the page!

Thank you!

**Comment by lexterror** [comment]
Im posting the Icons here in case you're interested!


![few](https://user-images.githubusercontent.com/16135535/136285845-c75a1488-5af8-46d4-a5c4-a5218bcebecc.gif)
![fog](https://user-images.githubusercontent.com/16135535/136285849-442d8e60-2265-4b68-9acc-d4a3556c3673.gif)
![rain](https://user-images.githubusercontent.com/16135535/136285850-014fe873-dac7-4983-869c-e8cfc03a5d5c.gif)
![sct](https://user-images.githubusercontent.com/16135535/136285851-56f5cefe-0a68-42e9-a2b2-870cae5ccb0b.gif)
![skc](https://user-images.githubusercontent.com/16135535/136285855-0b57db30-910b-48ee-8d1e-bd2d284ce0a6.gif)
![snow](https://user-images.githubusercontent.com/16135535/136285856-553c0f2e-8b6e-4b66-b128-e45991483675.gif)
![tsra](https://user-images.githubusercontent.com/16135535/136285858-fb0cb29d-094f-43dd-82d2-37928ac5b15c.gif)

I just updated the icons (Today)
Tonight I was able to make them transparent (For use with any background)

Thank you!
