### ISSUE TITLE
Submitting weather icon packs for use in your program?

### ISSUE THREAD

**Issue by lexterror** [ajwarnick/forecast-js#9]
Hi, 

I've been working on a weather icon pack for use with your program! I was wondering whether you would be interested in downloading my weather icon pack of future ones other people can make as well? I'm providing the weather icon pack for free and I don't want/need credit for it! I made it with "inkscape/gimp" and I'm pretty much done with the basic weather icons! If you think it's worthy please let me know! I wouldn't mind if you included it with you program either! If you really like it I'm wiling to create additional icons (example: extreme weather condition icons)

You can see the icon pack I made here: http://electrolex.myartsonline.com/wi.html

Thank you!

**Comment by lexterror** [comment]
Also: do you think it might be good to include a basic "UI" for your program like the one I made here: 

http://electrolex.myartsonline.com/index_02465.php

So users don't have to struggle with a basic layout!

**Comment by ajwarnick** [comment]
So I have tried to not package any images with the library (the icons I link to are from an example I have in a second repo), but I do link to [examples in the readme](https://github.com/ajwarnick/forecast-js#exemples). So if you have a codepen/codesandbox/glitch where you have made the source code easily reference-able I would love to include it.

**Comment by ajwarnick** [comment]
And if you want make the icons available to use it would be great if you made a repo for them.

**Comment by lexterror** [comment]
Hi ajwarnick!!!

Here's the glitch links:

https://harmless-lavish-cub.glitch.me
https://glitch.com/edit/#!/harmless-lavish-cub

I embedded the animations I made (they look really nice, I was adjusting them this morning)

Thank you!!!

**Comment by ajwarnick** [comment]
Great and I will update the read me with the glitch link. For linking to you would you like your website or github link?

**Comment by lexterror** [comment]
Hi ajwarnick!!!

Oh, I just thought you could use a forecast template for your app, so users can have a UI to start with! No need to link me! 

Thank you!!!

**Comment by ajwarnick** [comment]
I have added your example to the read me

https://github.com/ajwarnick/forecast-js/blob/master/readme.md#7-day-forecast-by-lexterror

**Comment by lexterror** [comment]
Hi ajwarnick,

Thank you!!!
